openapi: 3.0.0
x-stoplight:
  id: zvpj576gvy7j9
info:
  title: Backend API Final Project 4
  version: '1.0'
  description: The API documentation here contains all the api documentation to support the Binar Academy Final Project Backend Developer
  contact:
    name: Syifaul Qolbi
    email: syifaulqolbi32@gmail.com
servers:
  - url: 'https://antariksa-api.up.railway.app'
    description: Production Environtment
  - url: 'https://backend-4.up.railway.app/'
    description: Staging Environtment
paths:
  /auth/register:
    post:
      summary: Create Buyer Register Endpoint
      operationId: post-auth-register
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      email:
                        type: string
                      name:
                        type: string
                      role:
                        type: string
                x-examples:
                  Example 1:
                    status: true
                    message: Succes
                    data:
                      email: syifaul@gmail.com
                      name: Syifa
                      role: Buyer
              examples:
                Example 1:
                  value:
                    email: syifa@mail.com
                    name: Syifa
                    role: Buyer
        '400':
          description: email not match
        '403':
          description: email already used
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              x-examples:
                Example 1:
                  name: Syifa
                  email: syifa@mail.com
                  password: '123'
            examples:
              Example 1:
                value:
                  name: Syifa
                  email: syifa@mail.com
                  password: '123'
        description: In this body you can create new buyer
      description: ''
      tags:
        - Auth Endpoint
  /auth/login:
    post:
      summary: Login Buyer Endpoint
      operationId: post-auth-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                      role:
                        type: string
                x-examples:
                  Example 1:
                    status: true
                    data:
                      token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6IlN5aWZhIiwiZW1haWwiOiJzeWlmYXVscW9sYmkzNUBnbWFpbC5jb20iLCJyb2xlIjoiQnV5ZXIiLCJpYXQiOjE2Njk4Mzk2ODR9.Rg3zv3MGeGRwSYAvEoo76j6MLM0g_i9BWEnMyeXNU3U
                      role: Buyer
              examples:
                Example 1:
                  value:
                    status: true
                    data:
                      token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6IlN5aWZhIiwiZW1haWwiOiJzeWlmYXVscW9sYmkzNUBnbWFpbC5jb20iLCJyb2xlIjoiQnV5ZXIiLCJpYXQiOjE2Njk4Mzk2ODR9.Rg3zv3MGeGRwSYAvEoo76j6MLM0g_i9BWEnMyeXNU3U
                      role: Buyer
        '400':
          description: Email not found
        '401':
          description: Password doesn't match
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              x-examples:
                Example 1:
                  email: syifaulqolbi35@gmail.com
                  password: '123'
            examples:
              Example 1:
                value:
                  email: syifaulqolbi35@gmail.com
                  password: '123'
        description: In this endpoint you can login to your application
      tags:
        - Auth Endpoint
  /auth/forgot-password:
    post:
      summary: Forgot Password Endpoint
      operationId: post-auth-forgot-password
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              x-examples:
                Example 1:
                  email: syifaulqolbi32@gmail.com
            examples:
              Example 1:
                value:
                  email: syifasyifa123@gmail.com
        description: 'Masukkan email user yang ingin diubah password nya :)'
      tags:
        - Auth Endpoint
  /auth/reset-password:
    post:
      summary: Reset Password Endpoint
      operationId: post-auth-reset-password
      responses:
        '200':
          description: OK
      tags:
        - Auth Endpoint
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                new_password:
                  type: string
                confirm_new_password:
                  type: string
              x-examples:
                Example 1:
                  new_password: '1234'
                  confirm_new_password: '1234'
            examples:
              Example 1:
                value:
                  new_password: '1234'
                  confirm_new_password: '1234'
        description: 'Endpoint untuk reset password, silahkan dimasukkan new password dan confirm new password nya'
  /auth/whoami:
    get:
      summary: Profile Endpoint
      tags:
        - Auth Endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      email:
                        type: string
                      role:
                        type: string
                      gender:
                        type: 'null'
                      phone:
                        type: 'null'
                      iat:
                        type: integer
                x-examples:
                  Example 1:
                    status: false
                    message: succes
                    data:
                      id: 4
                      name: dadang
                      email: dada@mail.com
                      role: Buyer
                      gender: null
                      phone: null
                      iat: 1670253655
              examples:
                Example 1:
                  value:
                    status: false
                    message: succes
                    data:
                      id: 4
                      name: dadang
                      email: dada@mail.com
                      role: Buyer
                      gender: null
                      phone: null
                      iat: 1670253655
      operationId: get-auth-whoami
      description: Endpoint ini digunakan untuk cek profile
      parameters:
        - schema:
            type: string
          in: header
          required: true
          name: Authorization
  /list-airport:
    get:
      summary: Airport List Endpoint
      tags:
        - List Airport Endpoint
      responses:
        '200':
          description: Ok.. Data Airport
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        region:
                          type: string
                        code:
                          type:
                            - 'null'
                            - string
                x-examples:
                  Example 1:
                    status: true
                    message: Data dari Port API
                    data:
                      - name: Sultan Aji Muhammad Sulaiman Sepinggan International Airport
                        region: Kalimantan Timur (East Kalimantan)
                        code: BPN
                      - name: Dortheys Hiyo Eluay International Airport
                        region: Papua
                        code: DJJ
              examples:
                Example 1:
                  value:
                    status: true
                    message: Data Airport
                    data:
                      - name: Soekarno Hatta
                        region: Banten
                        code: CGK
      operationId: get-list-airport
      description: Endpoint ini untuk mengambil data list airport yang ada di Indonesia
  /search?:
    get:
      summary: Get All Data Search
      tags:
        - Search Endpoint
      responses:
        '200':
          description: OK
      operationId: get-search?
      description: This endpoint can show all data search
      parameters:
        - schema:
            type: string
          in: query
          name: Origin Airport
          description: Add origin airport
          required: true
        - schema:
            type: string
          in: query
          name: Destination Airport
          description: Add destination airport
          required: true
        - schema: {}
          in: query
          name: Departure Date
          description: Add departure date
          required: true
        - schema: {}
          in: query
          name: Arrival Date
          description: Add arrival date
          required: true
        - schema:
            type: string
          in: query
          name: Return Date
          description: Add return date
        - schema:
            type: integer
          in: query
          name: Total Passenger
          description: Add total passenger
          required: true
  /search-admin:
    parameters: []
    post:
      summary: Add schedule flight list
      operationId: post-search-admin
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      airlines:
                        type: string
                      depature_time:
                        type: string
                      arrival_time:
                        type: string
                      duration_time:
                        type: string
                      price:
                        type: string
                x-examples:
                  Example 1:
                    status: true
                    message: success
                    data:
                      airlines: Garuda
                      depature_time: '2022-12-10'
                      arrival_time: '2022-12-10'
                      duration_time: '6'
                      price: '6000000'
              examples:
                Example 1:
                  value:
                    status: true
                    message: success
                    data:
                      airlines: Garuda
                      depature_time: '2022-12-10'
                      arrival_time: '2022-12-10'
                      duration_time: '6'
                      price: '6000000'
        '400':
          description: Bad Request
      tags:
        - Search Endpoint
      description: Di endpoint ini admin dapat menambahkan list jadwal penerbangan
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                airlines:
                  type: string
                depature_time:
                  type: string
                arrival_time:
                  type: string
                duration_time:
                  type: string
                price:
                  type: string
              x-examples:
                Example 1:
                  airlines: Garuda
                  depature_time: '2022-12-10'
                  arrival_time: '2022-12-10'
                  duration_time: '6'
                  price: '6000000'
            examples:
              Example 1:
                value:
                  airlines: Garuda
                  depature_time: '2022-12-10'
                  arrival_time: '2022-12-10'
                  duration_time: '6'
                  price: '6000000'
        description: 'Kamu dapat memasukkan data berikut '
      parameters:
        - schema:
            type: string
          in: header
          name: authorization
          description: authorization for admin needed
  /search:
    parameters: []
    put:
      summary: Edit schedule list endpoint
      operationId: put-search
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      airlines:
                        type: string
                      depature_time:
                        type: string
                      arrival_time:
                        type: string
                      duration_time:
                        type: string
                      price:
                        type: string
                x-examples:
                  Example 1:
                    status: true
                    message: success
                    data:
                      airlines: Garuda
                      depature_time: '2022-12-10'
                      arrival_time: '2022-12-10'
                      duration_time: '6'
                      price: '6000000'
              examples:
                Example 1:
                  value:
                    status: true
                    message: success
                    data:
                      airlines: Garuda
                      depature_time: '2022-12-10'
                      arrival_time: '2022-12-10'
                      duration_time: '6'
                      price: '6000000'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      description: Diendpoint ini admin dapat mengubah jadwal penerbangan pesawat
      parameters:
        - schema:
            type: string
          in: header
          name: authorization
          description: only admin can access this endpoint
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                airlines:
                  type: string
                depature_time:
                  type: string
                arrival_time:
                  type: string
                duration_time:
                  type: string
                price:
                  type: string
              x-examples:
                Example 1:
                  airlines: Garuda
                  depature_time: '2022-12-10'
                  arrival_time: '2022-12-10'
                  duration_time: '6'
                  price: '6000000'
            examples:
              Example 1:
                value:
                  airlines: Garuda
                  depature_time: '2022-12-10'
                  arrival_time: '2022-12-10'
                  duration_time: '6'
                  price: '6000000'
        description: 'Hal hal yang bisa di edit, tidak harus semua field diedit'
      tags:
        - Search Endpoint
  '/search/:id':
    parameters: []
    delete:
      summary: Delete Schedule Flight List Endpoint
      operationId: delete-search---copy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                Example 1:
                  value:
                    message: Success delete data
      tags:
        - Search Endpoint
      description: Endpoint ini digunakan untuk menghapus Schedule Flight
      parameters:
        - schema:
            type: string
          in: header
          name: authorization
          description: only admin can delete data
components:
  securitySchemes: {}
